"""
Django settings for elecciones project.

Generated by 'django-admin startproject' using Django 4.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-ulq5vr$x6p!lvi#a$i)x0i1u+z5jy3!tnrn^dd@l9!+9$@-e74'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'usuarios',
    'catalogos',
    'generales',
    'promovido',
    "crispy_forms",
    "crispy_bootstrap5",
    "agenda",
    'configuracion',

    'django_postalcodes_mexico.apps.DjangoPostalcodesMexicoConfig',
    'votacion'
    # ...


]


CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"

CRISPY_TEMPLATE_PACK = "bootstrap5"
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'elecciones.urls'
import os 
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,"templates")],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                
                'usuarios.context_processors.profile_completion',  
                'usuarios.context_processors.user_groups',
                'usuarios.context_processors.group_context',
                'configuracion.context_processors.candidato_config_processor',

# Asegúrate de usar la ruta correcta a tu context processor

            ],
        },
    },
]

WSGI_APPLICATION = 'elecciones.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'es-mx'
LANGUAGES = [
    ('es', 'Spanish'),
]
TIME_ZONE = 'America/Mexico_City'


USE_I18N = True

USE_TZ = True
AUTH_USER_MODEL = 'usuarios.CustomUser'  # Reemplaza 'myapp' con el nombre de tu aplicación


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')


MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, "media")


STATICFILES_DIRS=[
    os.path.join(os.path.join(BASE_DIR,"static"))
]

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
JAZZMIN_SETTINGS = {
    "language_code": "es",

  # title of the window (Will default to current_admin_site.site_title if absent or None)
    "site_title": "MORENA",

    # Title on the login screen (19 chars max) (defaults to current_admin_site.site_header if absent or None)
    "site_header": "MORENA",
    "site_brand": "MORENA",

    # Logo to use for your site, must be present in static files, used for brand on top left
    "site_logo": "img/logo160x16021.png",

    "welcome_sign": "Bienvenido al Sistema MORENA",

    "changeform_format": "single",

    'icons':{

        'auth.user': "fas fa-user",
        'auth.group': "fas fa-users",





    }

}

LOGIN_REDIRECT_URL = 'menu'
LOGOUT_REDIRECT_URL = "home"

# Duración de la sesión en segundos (10 minutos)
# SESSION_COOKIE_AGE = 10
# # Actualizar el tiempo de expiración de la sesión en cada solicitud
# SESSION_SAVE_EVERY_REQUEST = True
LOGIN_URL = '/login/'
